### PR TITLE
Add support for generating documents with randomized Wikipedia pages

### PR DESCRIPTION
**Pull request by rcky844**
A change that add supports to generating documents with random Wikipedia pages so that you won't have to think of a random name each time to generate a page, and adds randomness to the generation process so that it gets accepted easily.

### CODE REVIEW

**Comment by rcky844** [comment]
The change sets this behaviour as default, please review and adjust if you don't like it.

**Comment by TipzRickyCheung** [comment]
Made it simpler, turns out setting default to "Special:Random" works better than their inbuilt function.

**Comment by rcky844** [comment]
I have added in another change that deals with DisambiguationError

**Comment by ytinyui** [comment]
How about selecting a random document when the title argument is not specified? This way we can avoid adding a new argument.

**Comment by rcky844** [comment]
> How about selecting a random document when the title argument is not specified? This way we can avoid adding a new argument.

I mean that's a decent idea, let me push again.

**Comment by rcky844** [comment]
We will need @rvaidun to check whether the edits to readme looks good.

**Comment by rvaidun** [comment]
changes look good to me.

**Pull request merged**
